name: Deploy EuphoriaBot to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 194.87.131.97
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/euphoriabot
          git pull origin main
          systemctl restart euphoriabot
          systemctl restart euphoriabot-api
          cd project
          npm install
          npm run build
          mkdir -p /var/www/euphoria
          rm -rf /var/www/euphoria/*
          cp -r dist/* /var/www/euphoria/
          systemctl restart nginx
          echo "✅ EuphoriaBot деплой завершен!"